#!/usr/bin/env python3
"""Protocol 19 is GENERATED from the state machine — it says so on its own second line.

In v2.0 nothing enforced that, so the document could drift from the code silently and
still point at a module path that no longer existed. Here the document has exactly one
producer, and validate_package.py fails if the file on disk differs by a single byte
from what this generator emits. Documentation drift stops being a discipline problem and
becomes a structurally impossible state.

    --check   compare only, exit 1 on drift
    (default) rewrite the document
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ORCH = os.path.dirname(HERE)
ROOT = os.path.dirname(ORCH)
sys.path.insert(0, ORCH)

from lawmax21.states import NEXT, OWNER_GATES, SCHEMAS, SEMANTIC, STATES  # noqa: E402

TARGET = os.path.join(ROOT, "immutable-package", "protocols", "19-DEEPSEEK-RUNNER-STATE-MACHINE.md")
SOURCE_OF_TRUTH = "executable-orchestrator/lawmax21/states.py"

NOTES = {
    "PACKAGE_VALIDATED": "full SHA-256 manifest, zero unlisted/missing, schemas enforceable",
    "EVIDENCE_VAULT_CERTIFIED": "every declared source present and non-empty",
    "CHARTER_FROZEN": "objective frozen before any architecture selection; Vision must be EVIDENCE_BACKED",
    "HIDDEN_BANK_COMMITTED": "merkle commitment + grader freeze + canary roster",
    "ATTESTED": "mode, paid-call count, package tree hash, no key material in builder scope",
    "REPOSITORY_RECONSTRUCTED": "every item carries executable evidence; UNKNOWN is allowed and explicit",
    "HISTORICAL_EVIDENCE_SYNTHESIZED": "prior studies mapped with sourced lessons",
    "GLOBAL_LAWMAX_MODEL_CERTIFIED": "proof-of-ingestion: zero uningested byte ranges, citations verified byte-exact",
    "TARGET_ARCHITECTURE_SEARCH": "independent explorer contexts; at least three distinct families",
    "TARGET_ARCHITECTURE_v0_REVIEWED": "OWNER GATE — signed approval bound to (gate, run, artifact hash)",
    "TARGET_ARCHITECTURE_v0_FROZEN": "v0 artifacts hash-pinned",
    "EVALUATION_PARAMETERS_FROZEN": "pareto dimensions and thresholds pinned separately from the charter",
    "SUBSTRATE_BUILDING": "shared capability substrate assembled in an isolated worktree",
    "SUBSTRATE_CERTIFIED": "visible suite passes across all capability slices",
    "ARCHITECTURE_DISCOVERY": "candidate register: at least two distinct mechanisms",
    "CANDIDATE_BUILDING": "each candidate written into its own worktree and compiled",
    "VISIBLE_CERTIFIED": "candidates measured head-to-head; a non-discriminating suite fails the guard",
    "FIDELITY_CERTIFIED": "ablation must move the score; hard-coded answers scanned",
    "PRIVATE_QUALIFICATION": "hidden shards, isolated candidate processes, canaries all denied",
    "PROVISIONAL_FRONTIER_MEMBER": "complete measured vector admitted to the frontier",
    "CEILING_ANALYSIS": "must name what the architecture cannot do",
    "SUCCESSOR_SEARCH": "evolutionary challenger from the reserved budget line",
    "RADICAL_CHALLENGER_SEARCH": "discontinuous challenger from the reserved budget line",
    "SIMPLIFICATION_CHALLENGE": "can a strictly simpler design match the frontier?",
    "FRONTIER_REVIEW": "dominance gate; only non-dominated candidates reach private shards",
    "PRIVATE_REPLICATION": "finalists replicated on a second sealed level",
    "ANTI_SATISFICING_AUDIT": "all eight checks resolved with evidence; unresolved items block",
    "HESA_CANDIDATE": "highest evidence-supported architecture; margin must be strictly positive",
    "FINAL_HOLDOUT_EVALUATION": "single-use holdout, enforced by an owner-side ledger",
    "ARCHITECTURE_EVIDENCE_SYNTHESIS": "useful / decorative / refuted, per mechanism",
    "TARGET_ARCHITECTURE_v1_REVIEWED": "OWNER GATE — signed approval bound to (gate, run, artifact hash)",
    "MIGRATION_PLAN_FROZEN": "OWNER GATE — waves with per-wave rollback; big-bang forbidden",
    "INDEPENDENT_AUDIT": "signed log verified, package unchanged, budget within ceiling",
    "COMMITTED": "OWNER GATE — the run's conclusion is admitted by the owner, not by the runner",
    "BEST_DISCOVERED_SO_FAR": "honest terminal state when the target was not reached",
    "HALTED": "honest terminal state on a blocking failure",
    "UNINITIALIZED": "no signed transition recorded yet",
}


def render():
    lines = [
        "# 19 — DEEPSEEK RUNNER STATE MACHINE (v2.1)",
        "",
        f"Source of truth: {SOURCE_OF_TRUTH} — this document is GENERATED by",
        "executable-orchestrator/tools/generate_protocol19.py and validate_package.py fails on any drift.",
        "",
        "Every transition requires, in order: (1) legality from the state derived from the SIGNED event",
        "log, (2) the declared artifact validating against its JSON Schema, (3) the state's semantic",
        "predicate, (4) for owner gates, an owner-signed approval bound to gate, run and artifact hash.",
        "File existence alone advances nothing.",
        "",
        "## States",
        "",
    ]
    for s in STATES:
        nxt = ", ".join(NEXT.get(s, [])) or "—"
        gate = OWNER_GATES.get(s)
        marks = []
        if s in SCHEMAS:
            marks.append("schema-guarded")
        if s in SEMANTIC:
            marks.append("semantic-guarded")
        if gate:
            marks.append(f"owner-gate:{gate}")
        lines.append(f"- **{s}** — {NOTES.get(s, '')} | next: {nxt} | guards: "
                     f"{', '.join(marks) if marks else 'log-legality only'}")
    lines += [
        "",
        "## Terminal honesty",
        "",
        "COMMITTED is not the only acceptable ending. BEST_DISCOVERED_SO_FAR and HALTED are first-class:",
        "a run that did not reach the target must say so rather than relabel a lesser result.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    want = render()
    if a.check:
        have = open(TARGET, encoding="utf-8").read() if os.path.exists(TARGET) else ""
        if have != want:
            print("PROTOCOL 19 DRIFT: the document does not match the state machine")
            return 1
        print("protocol 19: in sync with the state machine")
        return 0
    with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write(want)
    print(f"protocol 19 regenerated from {SOURCE_OF_TRUTH} ({len(STATES)} states)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
