#!/usr/bin/env python3
"""Authoritative zero-cost proof for National Observatory supremacy-search protocol.

Reuses the SAME production launcher, shared signed state machine, HTTP client, budget ledger and
owner-gate code. The only substituted component is a localhost DeepSeek-shape provider. PASS means
the control plane actually traversed and mechanically required the new research protocol; it does
not mean the mock architecture is scientifically supreme.
"""
import argparse
import glob
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ORCH = os.path.dirname(HERE)
ROOT = os.path.dirname(ORCH)
sys.path.insert(0, HERE)

import run_observatory_proof as legacy  # reusable transport/clone/gate/accounting helpers only

RUN_ID = legacy.RUN_ID
MODEL = legacy.MODEL
PORT = legacy.PORT
SUPREMACY_KEYS = [
    "search_forest_executed", "genome_saturated", "recombination_tested",
    "systems_arena_passed", "lower_bound_closed", "destroyer_survived",
    "public_supremacy_case",
]
GENOME_FIELDS = [
    "canonical_authority_seat", "evidence_primitive", "identity_model",
    "state_derivation_model", "temporal_model", "normative_effect_model",
    "consistency_commit_model", "replication_distribution_model", "trusted_core_topology",
    "provenance_proof_model", "publication_topology", "governance_evolution_model",
    "scaling_partition_model",
]


def read_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def write_json(path, obj):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=1, sort_keys=True)


def latest_numbered(root, prefix):
    paths = glob.glob(os.path.join(root, prefix + "*.json"))
    if not paths:
        raise RuntimeError(f"no artifact matches {prefix}*.json")
    def num(p):
        import re
        m = re.search(r"round(\d+)", os.path.basename(p))
        return int(m.group(1)) if m else -1
    return max(paths, key=num)


def verify_genome(genome):
    if not isinstance(genome, dict):
        return False
    for axis in GENOME_FIELDS:
        value = genome.get(axis)
        if not isinstance(value, dict) or not isinstance(value.get("class"), str) or not value["class"]:
            return False
        if not isinstance(value.get("detail"), str) or len(value["detail"]) < 10:
            return False
    return True


def signature(genome):
    return tuple(genome[a]["class"] for a in GENOME_FIELDS)


def verify_search_and_build(runtime):
    forest = read_json(os.path.join(runtime, "architecture", "search_forest.json"))
    fsum = forest.get("summary") or {}
    if fsum.get("lineages") != 15 or fsum.get("general_lineages") != 6 or fsum.get("anti_attractor_lineages") != 9:
        raise RuntimeError(f"wrong search-forest lineage census: {fsum}")
    if int(fsum.get("seeds", 0)) < 90 or int(fsum.get("selected_finalists", 0)) < 12:
        raise RuntimeError("search forest did not create/select enough structural alternatives")
    if fsum.get("distance_basis") != "controlled_genome_class":
        raise RuntimeError("search diversity is not based on controlled structural genome classes")
    if fsum.get("prior_cp2_visible") is not False:
        raise RuntimeError("prior CP2 leaked into independent search forest")

    proposals = read_json(os.path.join(runtime, "architecture", "proposals.json"))
    if proposals.get("search_mode") != "SUPREMACY_SEARCH_FOREST_V1" or proposals.get("prior_cp2_visible") is not False:
        raise RuntimeError("v0 proposals were not generated by the blind supremacy search forest")
    props = proposals.get("proposals") or []
    if len(props) < 12:
        raise RuntimeError("fewer than 12 structural finalists reached the v0 gate")
    sigs = []
    for p in props:
        if not verify_genome(p.get("genome")):
            raise RuntimeError(f"proposal {p.get('seed_id')} has incomplete categorical genome")
        if not isinstance(p.get("formalization"), dict) or len(p["formalization"].get("invariant_set", [])) < 8:
            raise RuntimeError(f"proposal {p.get('seed_id')} lacks invariant formalization")
        if not isinstance(p.get("prebuild_destroyer"), dict):
            raise RuntimeError(f"proposal {p.get('seed_id')} lacks prebuild destroyer evidence")
        sigs.append((p.get("seed_id"), signature(p["genome"])))
    for i, (aid, a) in enumerate(sigs):
        for bid, b in sigs[i + 1:]:
            d = sum(x != y for x, y in zip(a, b))
            if d < 2:
                raise RuntimeError(f"finalists {aid}/{bid} differ on only {d} controlled genome classes")

    gate = read_json(os.path.join(runtime, "gates", "v0_subject.json"))
    if gate.get("builder_handoff") != "COMPLETE_BLUEPRINT_PLUS_FORMALIZATION_REQUIRED":
        raise RuntimeError("v0 owner gate does not bind complete blueprint + formalization")
    if int(gate.get("structural_finalists", 0)) < 12 or not gate.get("supremacy_contract_sha256"):
        raise RuntimeError("v0 owner gate does not bind structural supremacy search")

    built = read_json(os.path.join(runtime, "candidates", "built.json"))
    if built.get("complete_blueprint_handoff") is not True or built.get("formalization_handoff") is not True:
        raise RuntimeError("builder handoff lost blueprint/formalization")
    if built.get("probabilistic_fidelity_is_advisory") is not True:
        raise RuntimeError("probabilistic blueprint-fidelity critics still have elimination authority")
    rows = built.get("built") or []
    if len(rows) < 2:
        raise RuntimeError("fewer than two formalized architectures produced executable candidates")
    for row in rows:
        if not row.get("blueprint_sha256") or not row.get("formalization_sha256"):
            raise RuntimeError(f"built candidate {row.get('candidate_id')} lost design hashes")
        if int(row.get("implementation_attempts", 0)) != 3:
            raise RuntimeError(f"built candidate {row.get('candidate_id')} did not receive best-of-three implementation search")
        if not row.get("systems_candidate_sha256"):
            raise RuntimeError(f"built candidate {row.get('candidate_id')} has no durable systems implementation")

    return {"search_forest": fsum, "structural_finalists": len(props), "built_candidates": len(rows)}


def verify_prefrontier_systems(runtime):
    path = latest_numbered(os.path.join(runtime, "reports"), "private-qualification-round")
    q = read_json(path)
    systems = q.get("systems_qualification") or []
    if not systems:
        raise RuntimeError("private qualification contains no durable systems qualification")
    if any(x.get("passed") is not True for x in systems):
        raise RuntimeError("zero-cost proof expected every reference durable candidate to qualify")
    for row in systems:
        if not isinstance(row.get("revision_history"), list):
            raise RuntimeError("durable qualification did not expose revision history")

    rep_path = latest_numbered(os.path.join(runtime, "reports"), "private-replication-round")
    rep = read_json(rep_path)
    sr = rep.get("systems_replication") or []
    if not sr or any(x.get("passed") is not True for x in sr):
        raise RuntimeError("independent durable systems replication did not pass for all proof finalists")
    return {"qualification_artifact": path, "qualified": len(systems),
            "replication_artifact": rep_path, "replicated": len(sr)}


def verify_crown(runtime, summary, run):
    esc = summary.get("escalation") or {}
    sup = esc.get("supremacy") or {}
    missing = [k for k in SUPREMACY_KEYS if sup.get(k) is not True]
    if missing:
        raise RuntimeError("terminal proof lacks supremacy conditions: " + ", ".join(missing))
    if int(sup.get("genome_dry_waves", 0)) < 3 or int(sup.get("known_genomes", 0)) < 12:
        raise RuntimeError("controlled structural-genome saturation was not established")
    if int(sup.get("recombinations", 0)) < 1:
        raise RuntimeError("no executable recombination was recorded")
    if sup.get("third_party_endorsement_claimed") is not False:
        raise RuntimeError("terminal proof contains unsupported third-party endorsement")

    inc = esc.get("incumbent")
    systems_path = os.path.join(runtime, "reports", f"systems-crown-{inc}.json")
    systems = read_json(systems_path)
    if systems.get("status") != "PASS" or systems.get("passed") is not True:
        raise RuntimeError("50K-event crown durable systems arena did not pass")
    tests = systems.get("tests") or {}
    required = [
        "initial_durable_state", "restart_identity", "duplicate_idempotence",
        "concurrent_access_integrity", "concurrent_eventual_root_match",
        "crash_was_actually_observed", "crash_restart_integrity",
        "deterministic_large_rebuild", "large_history_integrity",
        "publication_root_consistency",
    ]
    bad = [k for k in required if tests.get(k) is not True]
    if bad:
        raise RuntimeError("crown durable systems arena missing passing witnesses: " + ", ".join(bad))
    corruption = tests.get("corruption_detection_recovery") or {}
    if corruption.get("passed") is not True:
        raise RuntimeError("load-bearing authority corruption/recovery witness failed")
    large = systems.get("large_history") or {}
    if int(large.get("events_per_rebuild", 0)) < 50000:
        raise RuntimeError("crown durable systems campaign did not reach 50K events per rebuild")

    lower = read_json(os.path.join(runtime, "architecture", "lower_bounds.json"))
    if lower.get("closed") is not True or len(lower.get("reports") or []) != 3:
        raise RuntimeError("independent lower-bound campaign did not close")
    destroyers = read_json(os.path.join(runtime, "architecture", "final_destroyers.json"))
    if destroyers.get("survived") is not True or len(destroyers.get("reports") or []) != 3:
        raise RuntimeError("final legal/systems/minimality destroyer campaign did not close")
    case = read_json(os.path.join(runtime, "architecture", "SUPREMACY-CASE.json"))
    if case.get("mechanically_supported") is not True or case.get("claim_level") != "EVIDENCE_SUPPORTED_SUPREMACY":
        raise RuntimeError("public supremacy case is not mechanically supported")
    if case.get("third_party_endorsement_claimed") is not False or len(case.get("falsifiers") or []) < 3:
        raise RuntimeError("supremacy case contains endorsement fiction or lacks falsifiers")

    required_gates = {"GATE-ARCH-V0", "GATE-ARCH-V1", "GATE-MIGRATION", "GATE-COMMIT"}
    if not required_gates.issubset(set(run.get("gates") or [])):
        raise RuntimeError(f"proof did not traverse all owner gates: {run.get('gates')}")
    return {"supremacy": sup, "systems_crown": systems,
            "lower_bounds_closed": True, "destroyers_survived": True,
            "supremacy_case_supported": True}


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--canonical-repo", required=True)
    ap.add_argument("--cp1-evidence", required=True)
    ap.add_argument("--prior-cp2", required=True)
    ap.add_argument("--keep", action="store_true")
    a = ap.parse_args(argv)

    target, cp1, prior = map(os.path.abspath, (a.canonical_repo, a.cp1_evidence, a.prior_cp2))
    temp = legacy.short_temp_workspace(); dest = os.path.join(temp, "r"); runtime = os.path.join(temp, "rt")
    mock = None
    result = {"proof": "national-observatory-supremacy-zero-cost-e2e-v4", "paid_api_calls": 0,
              "workspace": temp, "runtime": runtime}
    try:
        source_head = legacy.clone_disposable(dest); result["source_head"] = source_head

        # The known no-resend boundary remains a precondition of the new, much longer search.
        nr = legacy.py(os.path.join(dest, "executable-orchestrator", "tools", "prove_no_resend_contract.py"), cwd=dest)
        result["no_resend_contract"] = {"rc": nr.returncode, "tail": ((nr.stdout or "") + (nr.stderr or ""))[-2500:]}
        if nr.returncode != 0:
            raise RuntimeError("no-resend contract regression failed")

        setup = legacy.py(os.path.join(dest, "setup_observatory.py"), "--run-id", RUN_ID,
                          "--budget-usd", "25", "--tokens", "10000000", "--calls", "3000", "--days", "3",
                          "--qualification", "3", "--replication", "2", "--holdout", "2", cwd=dest)
        result["setup"] = {"rc": setup.returncode, "tail": ((setup.stdout or "") + (setup.stderr or ""))[-4000:]}
        if setup.returncode != 0:
            raise RuntimeError("setup_observatory failed\n" + result["setup"]["tail"])

        # Calibrate the hardened durable arena independently before the tournament depends on it.
        sys_ref = os.path.join(dest, "benchmark", "observatory_systems_reference_candidate.py")
        sys_out = os.path.join(dest, "proof", "systems-reference-calibration.json")
        sc = legacy.py(os.path.join(dest, "private-evaluator", "evaluator", "observatory_systems_arena.py"),
                       "--candidate", sys_ref, "--out", sys_out, "--large-events", "5000",
                       cwd=dest, timeout=1200)
        result["systems_reference_calibration"] = {"rc": sc.returncode, "tail": ((sc.stdout or "") + (sc.stderr or ""))[-4000:]}
        if sc.returncode != 0 or not os.path.exists(sys_out) or read_json(sys_out).get("status") != "PASS":
            raise RuntimeError("hardened durable systems calibration failed\n" + result["systems_reference_calibration"]["tail"])

        owner_key = os.path.join(dest, "private-evaluator", "owner-held-secrets", "OWNER.key")
        endpoint = f"http://127.0.0.1:{PORT}/chat/completions"
        pre = legacy.py(os.path.join(dest, "run_observatory.py"), "--preflight", "--run-id", RUN_ID,
                        "--endpoint", endpoint, "--model", MODEL, "--backend", "subprocess",
                        "--runtime", runtime, "--canonical-repo", target,
                        "--cp1-evidence", cp1, "--prior-cp2", prior, cwd=dest)
        result["preflight"] = {"rc": pre.returncode, "tail": ((pre.stdout or "") + (pre.stderr or ""))[-5000:]}
        if pre.returncode != 0:
            raise RuntimeError("Observatory supremacy preflight failed\n" + result["preflight"]["tail"])

        mock_script = os.path.join(dest, "executable-orchestrator", "tools", "mock_observatory_server.py")
        mock = subprocess.Popen([sys.executable, mock_script, "--port", str(PORT)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if not legacy.wait_port(PORT):
            out, err = mock.communicate(timeout=2)
            raise RuntimeError("supremacy mock server did not start\n" + (out or "") + (err or ""))

        run = legacy.drive_launch(dest, target, cp1, prior, runtime, owner_key, endpoint)
        result["launch"] = run
        if not run["completed"]:
            raise RuntimeError("shared supremacy state-machine rehearsal did not complete")
        if not run["crashed_and_resumed"]:
            raise RuntimeError("crash/resume drill did not actually crash and resume")

        summary = read_json(os.path.join(runtime, "reports", "run_summary.json")); result["run_summary"] = summary
        if summary.get("final_state") != "COMMITTED" or not summary.get("log_verified"):
            raise RuntimeError(f"expected verified COMMITTED, got {summary.get('final_state')}")
        if int((summary.get("budget") or {}).get("spent", {}).get("calls", 0)) <= 0:
            raise RuntimeError("mock HTTP path recorded zero model calls")
        esc = summary.get("escalation") or {}
        if any(k in esc for k in ("consciousness", "integration_attested", "credited_layers")):
            raise RuntimeError("legacy LAWMAX terminal semantics leaked into Observatory supremacy proof")

        reality = read_json(os.path.join(runtime, "reality", "REPOSITORY-REALITY-MODEL.json"))
        history = read_json(os.path.join(runtime, "reality", "HISTORICAL-EXPERIMENT-MAP.json"))
        if reality.get("repository_archaeology_api_calls") != 0 or history.get("prior_cp2_content_read") is not False:
            raise RuntimeError("sealed CP1 reuse / CP2 quarantine contract failed")

        result["search_and_build"] = verify_search_and_build(runtime)
        result["prefrontier_systems"] = verify_prefrontier_systems(runtime)
        result["crown"] = verify_crown(runtime, summary, run)

        audit = read_json(os.path.join(runtime, "audit", "independent_audit.json"))
        if not audit.get("immutable_package_unchanged") or audit.get("hidden_disclosed_to_builder"):
            raise RuntimeError("independent audit failed immutable/hidden invariants")
        result["independent_audit"] = audit
        result["currency_accounting"] = legacy.verify_currency_accounting(runtime, summary, audit)
        result["status"] = "PASS"
    except Exception as exc:
        result["status"] = "FAIL"; result["reason"] = str(exc)
    finally:
        if mock is not None:
            mock.terminate()
            try: mock.wait(timeout=3)
            except subprocess.TimeoutExpired: mock.kill()
        out = os.path.join(ROOT, "proof", "national-observatory-supremacy-zero-cost-e2e.json")
        write_json(out, result)
        print(json.dumps(result, ensure_ascii=False, indent=1, sort_keys=True)); print("proof report:", out)
        if a.keep or result.get("status") != "PASS":
            print("disposable proof directory retained:", temp)
        else:
            shutil.rmtree(temp, ignore_errors=True)
    return 0 if result.get("status") == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
